# site settings
title: Forty
subtitle: by HTML5 UP
email: francescogallo.fotografia@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://francescogallo.fotografia.it  
author: Francesco Gallo
street_address: via Mariti 17
city: Firenze
state: IT
zip_code: 50127
country: Italia 
phone: 3331341928

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/wickerman66
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/francescogallo_fotografo/
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
theme: forty
